# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
